repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest
        entry: pytest -v --maxfail=1 --disable-warnings
        language: system
        pass_filenames: false